dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

stages:
  - lint
  - test

matrix:
  include:
    - stage: lint
      name: flake8
      python: '3.7'

install:
  - pip install tox-travis

script:
  - tox